---

- include_vars: vars/main.yml

- name: Initialize PostgreSQL
  command: "/usr/pgsql-{{ db_version }}/bin/postgresql-{{ db_version }}-setup initdb"
  args:
    creates: "{{ pg_data_dir }}/PG_VERSION"
  register: command_output
  failed_when: command_output.rc != 0
  changed_when: false

- name: Display Command Output
  debug:
    var: command_output.stdout_lines

- name: Enable and Start PostgreSQL
  systemd:
    name: "{{ postgre_service }}"
    enabled: yes
    state: started
